/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;
/**
 *
 * @author titih
 */
public class ViewDeConnexion extends javax.swing.JFrame {

    /**
     * Creates new form ViewDeConnexion
     */
    public ViewDeConnexion() {
        /*java.awt.EventQueue.invokeLater(new Runnable() {
       public void run() {
        new ViewDeConnexion().setVisible(true);
     }
      });*/
        etat_bouton1 = 0;
        etat_bouton2 = 0;
        System.out.println("yooooooooooooooo");
    }
    
    public void Affichage() {
        initComponents();
        //System.out.println("yooooooooooooooo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 100));
        setMinimumSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 204));
        jButton2.setText("Inscription");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 360, 240, 90);

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Se Connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 480, 240, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/OnlineMarket.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        etat_bouton1 = 1;
        System.out.println(etat_bouton1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        etat_bouton2 = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    public int GetBouton1() {
        return etat_bouton1;
    }

    public int GetBouton2() {
        return etat_bouton2;
    }

    public void setBouton1(int nombre) {
        etat_bouton1 = nombre;
    }

    public void setBouton2(int nombre) {
        etat_bouton2 = nombre;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException ex

    
        ) {
            java.util.logging.Logger.getLogger(ViewDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex

    
        ) {
            java.util.logging.Logger.getLogger(ViewDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex

    
        ) {
            java.util.logging.Logger.getLogger(ViewDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex

    
        ) {
            java.util.logging.Logger.getLogger(ViewDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
     
     }
    public int etat_bouton1;
    public int etat_bouton2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
