/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author titih
 */
public class ViewPageFruit extends javax.swing.JFrame {

    /**
     * Creates new form ViewPageFruit
     */
    public ViewPageFruit() {
        /*if (type == "Fruit") {
            TypeFruit();
        }*/
        // jButton1.setText();
    }

    public void init() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 20));
        setMinimumSize(new java.awt.Dimension(1260, 960));
        setPreferredSize(new java.awt.Dimension(1280, 1000));
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flèche.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 160, 100, 90);

        jButton10.setBackground(new java.awt.Color(204, 255, 204));
        jButton10.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(650, 690, 210, 90);

        jButton11.setBackground(new java.awt.Color(204, 255, 204));
        jButton11.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(30, 300, 210, 90);

        jButton12.setBackground(new java.awt.Color(204, 255, 204));
        jButton12.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(340, 300, 210, 90);

        jButton13.setBackground(new java.awt.Color(204, 255, 204));
        jButton13.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 51, 51));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(650, 300, 210, 90);

        jButton14.setBackground(new java.awt.Color(204, 255, 204));
        jButton14.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 51, 51));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(30, 500, 210, 90);

        jButton15.setBackground(new java.awt.Color(204, 255, 204));
        jButton15.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 51, 51));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(340, 500, 210, 90);

        jButton16.setBackground(new java.awt.Color(204, 255, 204));
        jButton16.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 51, 51));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(650, 500, 210, 90);

        jButton17.setBackground(new java.awt.Color(204, 255, 204));
        jButton17.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 51, 51));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(30, 690, 210, 90);

        jButton18.setBackground(new java.awt.Color(204, 255, 204));
        jButton18.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton18.setForeground(new java.awt.Color(51, 51, 51));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(340, 690, 210, 90);

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("azfboazf");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(345, 270, 250, 40);

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("gzegz");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(655, 660, 270, 40);

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("gzegz");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(35, 270, 260, 40);

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("gzegz");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(655, 270, 270, 40);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("gzegz");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(35, 470, 260, 40);

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("gzegz");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(345, 470, 260, 40);

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setText("gzegz");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(655, 470, 250, 40);

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setText("gzegz");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(35, 660, 250, 40);

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setText("gzegz");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(345, 660, 260, 40);

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1170, 850, 80, 30);

        jTextField1.setText("Quantite");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(730, 790, 60, 24);

        jTextField2.setText("Quantite");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 400, 73, 24);

        jTextField3.setText("Quantite");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(410, 400, 60, 24);

        jTextField4.setText("Quantite");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(730, 400, 60, 24);

        jTextField5.setText("Quantite");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(100, 600, 60, 24);

        jTextField6.setText("Quantite");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(420, 600, 60, 24);

        jTextField7.setText("Quantite");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(730, 600, 60, 24);

        jTextField8.setText("Quantite");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(100, 790, 60, 24);

        jTextField9.setText("Quantite");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(420, 790, 60, 24);

        jButton1.setBackground(new java.awt.Color(205, 254, 205));
        jButton1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton1.setText("Payer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1010, 880, 220, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/page_fruits.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1890, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BoutonRetour = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        etatBouton10 = 1;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        etatBouton11 = 1;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        etatBouton12 = 1;
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        etatBouton13 = 1;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        etatBouton14 = 1;
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        etatBouton15 = 1;
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        etatBouton16 = 1;
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        etatBouton17 = 1;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        etatBouton18 = 1;
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField2.getText());

            if (ListTextFields.get(0).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField2.setText("VIDE");

            } else {
                ListTextFields.set(0, jTextField2.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(0).equals("vide")) {

                jTextField2.setText("VIDE");
            } else {
                jTextField2.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField1.getText());
            if (ListTextFields.get(8).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField1.setText("VIDE");
            } else {
                ListTextFields.set(8, jTextField1.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(8).equals("vide")) {

                jTextField1.setText("VIDE");
            } else {
                jTextField1.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField3.getText());
            if (ListTextFields.get(1).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField3.setText("VIDE");

            } else {
                ListTextFields.set(1, jTextField3.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(1).equals("vide")) {

                jTextField3.setText("VIDE");
            } else {
                jTextField3.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField4.getText());
            if (ListTextFields.get(2).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField4.setText("VIDE");

            } else {
                ListTextFields.set(2, jTextField4.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(2).equals("vide")) {

                jTextField4.setText("VIDE");
            } else {
                jTextField4.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField5.getText());
            if (ListTextFields.get(3).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField5.setText("VIDE");

            } else {
                ListTextFields.set(3, jTextField5.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(3).equals("vide")) {

                jTextField5.setText("VIDE");
            } else {
                jTextField5.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField6.getText());
            if (ListTextFields.get(4).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField6.setText("VIDE");

            } else {
                ListTextFields.set(4, jTextField6.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(4).equals("vide")) {

                jTextField6.setText("VIDE");
            } else {
                jTextField6.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField7.getText());
            if (ListTextFields.get(5).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField7.setText("VIDE");

            } else {
                ListTextFields.set(5, jTextField7.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(5).equals("vide")) {

                jTextField7.setText("VIDE");
            } else {
                jTextField7.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField8.getText());
            if (ListTextFields.get(6).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField8.setText("VIDE");

            } else {
                ListTextFields.set(6, jTextField8.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
           if (ListTextFields.get(6).equals("vide")) {

                jTextField8.setText("VIDE");
            } else {
                jTextField8.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
        try {
            int Blindage = Integer.parseInt(jTextField9.getText());
            if (ListTextFields.get(7).equals("vide")) {
                JOptionPane.showMessageDialog(this, "Il n y a pas de stock pour ce produit !");
                jTextField9.setText("VIDE");

            } else {
                ListTextFields.set(7, jTextField9.getText());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La valeur rentree n est pas correcte");
            if (ListTextFields.get(7).equals("vide")) {

                jTextField9.setText("VIDE");
            } else {
                jTextField9.setText("Quantite");
            }
        }
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        etatBoutonPayer = 1;
        /*  int n = JOptionPane.showConfirmDialog(this,
    "Avez-vous deja enregistre votre carte dans votre profil ?",
    "An Inane Question",
    JOptionPane.YES_NO_OPTION);*/
        //System.out.println("Valeur anel: " + n);
        // JOptionPane.showMessageDialog(this, "The only way to close this dialog is by\n"  + "pressing one of the following buttons.\n" + "Do you understand?" +JOptionPane.QUESTION_MESSAGE + JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void AfficherFond() {
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/page_fruits.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1890, 1000);
    }

    public void CreerNewJlabel(int coordY, String texte, String prix) { //  on va creer un nouveau label lorsqu'il y a une nouvelle colonne

        javax.swing.JLabel jLabel5 = new JLabel(texte);

        // jLabel5.setText(texte);
        // getContentPane().add(jLabel5);
        jLabel5.setBounds(1000, coordY, 210, 40);
        jLabel5.setVisible(true);
        getContentPane().add(jLabel5);

        javax.swing.JLabel jLabel6 = new JLabel(prix);

        // jLabel5.setText(texte);
        // getContentPane().add(jLabel5);
        jLabel6.setBounds(1210, coordY, 210, 40);
        jLabel6.setVisible(true);
        getContentPane().add(jLabel6);
    }

    public void PrixTotale(double prix) {
        DecimalFormat df = new DecimalFormat("0.00");
        jLabel11.setText("" + df.format(prix));
    }

    public void SetBouton_Texte(String nom, int numeroBouton, String texteAfficher, int stock) { // on change le nom des boutons
        if (numeroBouton == 1) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField2.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton11.setVisible(true);
            jLabel4.setVisible(true);
            jLabel4.setText(texteAfficher);
            jButton11.setText(nom);

        } else if (numeroBouton == 2) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField3.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton12.setVisible(true);
            jLabel3.setVisible(true);
            jLabel3.setText(texteAfficher);
            jButton12.setText(nom);
        } else if (numeroBouton == 3) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField4.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton13.setVisible(true);
            jLabel5.setVisible(true);
            jLabel5.setText(texteAfficher);
            jButton13.setText(nom);
        } else if (numeroBouton == 4) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField5.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton14.setVisible(true);
            jLabel6.setVisible(true);
            jLabel6.setText(texteAfficher);
            jButton14.setText(nom);
        } else if (numeroBouton == 5) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField6.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton15.setVisible(true);
            jLabel7.setVisible(true);
            jLabel7.setText(texteAfficher);
            jButton15.setText(nom);
        } else if (numeroBouton == 6) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField7.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton16.setVisible(true);
            jLabel8.setVisible(true);
            jLabel8.setText(texteAfficher);
            jButton16.setText(nom);
        } else if (numeroBouton == 7) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField8.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton17.setVisible(true);
            jLabel9.setVisible(true);
            jLabel9.setText(texteAfficher);
            jButton17.setText(nom);
        } else if (numeroBouton == 8) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField9.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }
            jButton18.setVisible(true);
            jLabel10.setVisible(true);
            jLabel10.setText(texteAfficher);
            jButton18.setText(nom);
        } else if (numeroBouton == 9) {
            if (stock == 0) {
                ListTextFields.add("vide");
                jTextField1.setText("VIDE");
            } else {
                ListTextFields.add("Quantite");
            }

            jButton10.setVisible(true);
            jLabel2.setVisible(true);
            jLabel2.setText(texteAfficher);
            jButton10.setText(nom);
        }

    }

    public void afficherErreur(String erreur)
    {
         JOptionPane.showMessageDialog(this, erreur);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPageFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPageFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPageFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPageFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    //affichage 
    public int BoutonRetour = 0;
    public int etatBouton10 = 0;
    public int etatBouton11 = 0;
    public int etatBouton12 = 0;
    public int etatBouton13 = 0;
    public int etatBouton14 = 0;
    public int etatBouton15 = 0;
    public int etatBouton16 = 0;
    public int etatBouton17 = 0;
    public int etatBouton18 = 0;
    public int etatBoutonPayer = 0;
    public ArrayList<String> ListTextFields = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
