/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraphique;

import java.awt.Point;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author titih
 */
public class ViewEmployeMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmployeMenu
     */
    public ViewEmployeMenu() {
        for (int i = 0; i < 9; i++) {
            ListTextFields.add("");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1260, 1000));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("Quantite");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(990, 840, 110, 40);

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(51, 51, 51));
        jTextField6.setText("Quantite");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(990, 520, 110, 40);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setText("Quantite");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 520, 110, 40);

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setText("Quantite");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(580, 520, 110, 40);

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(51, 51, 51));
        jTextField7.setText("Quantite");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(130, 680, 110, 40);

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(51, 51, 51));
        jTextField8.setText("Quantite");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(580, 680, 110, 40);

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(51, 51, 51));
        jTextField11.setText("Quantite");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(580, 840, 110, 40);

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(51, 51, 51));
        jTextField10.setText("Quantite");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(130, 840, 110, 40);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 480, 140, 50);

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(51, 51, 51));
        jTextField9.setText("Quantite");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(990, 680, 110, 40);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nom");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(990, 480, 140, 50);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nom");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(990, 800, 140, 50);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nom");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 480, 140, 50);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Nom");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 640, 140, 50);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nom");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 800, 140, 50);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nom");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(580, 640, 140, 50);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Nom");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(580, 800, 140, 50);

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Nom");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(990, 640, 140, 50);

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruit", "Viande", "Poisson", "Patisserie", "Menager", "Legumes" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(390, 160, 360, 40);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prix Unitaire", "Lot Promotion", "Prix Promotion", "Stock" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(630, 360, 470, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/frashSale.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(900, 440, 220, 230);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DossierClient.jpg"))); // NOI18N
        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 440, 220, 230);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ExamensVentes.jpg"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 440, 220, 230);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/flèche.jpg"))); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(820, 160, 96, 87);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 300, 1150, 403);

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(51, 51, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Nom", "Prenom", "Adresse", "Telephone", "Date"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 260, 880, 680);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1170, 915, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BoutonInventaire = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BoutonDossierClient = 1;

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BoutonExamVente = 1;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        ProduitChoisi = jComboBox1.getSelectedItem().toString();
        System.out.println(ProduitChoisi);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        CasePointee = jTable1.getSelectedRow();
        Object test = jTable1.getValueAt(CasePointee, 0);
        DatePointee = test.toString();
        System.out.println("la case selectionne est :" + CasePointee + "et date :" + DatePointee);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        BoutonRetour = 1;
        // jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuEmploye.png"))); // NOI18N        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        CasePointee = jTable2.getSelectedRow();
        Object test = jTable2.getValueAt(CasePointee, 5);
        DatePointee = test.toString();
        test = jTable2.getValueAt(CasePointee, 0);
        Username = test.toString();
        System.out.println("la case selectionne est :" + CasePointee + "et date :" + DatePointee + "et username est " + Username);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        ItemChoisi = jComboBox2.getSelectedItem().toString();
        System.out.println(ItemChoisi);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(8, jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(0, jTextField4.getText());
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(1, jTextField5.getText());
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(2, jTextField6.getText());
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(3, jTextField7.getText());
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(4, jTextField8.getText());
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(5, jTextField9.getText());
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(6, jTextField10.getText());
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
        ListTextFields.set(7, jTextField11.getText());
    }//GEN-LAST:event_jTextField11ActionPerformed

    public void AjouterLigneTab(String ListInfo, int j) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (j == 0) {
            Object[] row = {ListInfo};

            model.addRow(row);

        } else {
            int taille = jTable1.getRowCount();
            for (int i = 0; i < taille; i++) {
                model.removeRow(0);
                System.out.println("passeeeeeeeeee");
            }
        }

    }

    public int ModifyTextFieldsInventaire() {
        for (int i = 0; i < 9; i++) {
            if (!ListTextFields.get(i).equals("")) {
                return i;
            }
        }
        return -1;
    }

    public void AjouterLigneTab2(String[] ListInfo) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        Object[] row = {ListInfo[0], ListInfo[1], ListInfo[2], ListInfo[3], ListInfo[4], ListInfo[5]};
        model.addRow(row);

    }

    public void InterfaceExamVente(int i) {
        if (i == 0) {
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton4.setVisible(false);
            jComboBox2.setLocation(new Point(390, 160));
            jComboBox2.setVisible(true);
            jTable1.setVisible(true);
            jScrollPane1.setVisible(true);
            jButton5.setVisible(true);
        } else {
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton4.setVisible(true);
            jComboBox1.setVisible(false);
            jTable1.setVisible(false);
            jScrollPane1.setVisible(false);
            jButton5.setVisible(false);
        }

    }

    public void Menu() {
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jTextField1.setVisible(false);
        jTextField6.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField11.setVisible(false);;
        jTextField10.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        jButton5.setVisible(false);
        jTable2.setVisible(false);
        jScrollPane2.setVisible(false);
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 460, 1130, 450);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tableau.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 180, 800, 687);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AjoutMenuEmploye.jpg"))); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuEmploye.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1260, 980);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(false);

        // jComboBox1.setVisible(false);
    }

    public void DossierClient() {
        jComboBox1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jTextField1.setVisible(false);
        jTextField6.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField11.setVisible(false);;
        jTextField10.setVisible(false);
        jComboBox2.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        jButton5.setVisible(true);
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondDossierClient.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1260, 980);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondDossierClient.png"))); // NOI18N
        CasePointee = -1;
        DatePointee = "";
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jTable2.setVisible(true);
        jScrollPane2.setVisible(true);
        jLabel1.setVisible(true);
        jLabel4.setVisible(false);
    }

    public void CreerNewJlabel(int coordY, String texte, String prix) { //  on va creer un nouveau label lorsqu'il y a une nouvelle colonne
        System.out.println(texte + "    " + prix);
        javax.swing.JLabel jLabel5 = new JLabel(texte);

        // jLabel5.setText(texte);
        // getContentPane().add(jLabel5);
        jLabel5.setBounds(1000, coordY, 210, 40);
        jLabel5.setVisible(true);
        getContentPane().add(jLabel5);

        javax.swing.JLabel jLabel6 = new JLabel(prix);

        // jLabel5.setText(texte);
        // getContentPane().add(jLabel5);
        jLabel6.setBounds(1210, coordY, 210, 40);
        jLabel6.setVisible(true);
        getContentPane().add(jLabel6);
    }

    public void PrixTotale(double prix) {
        DecimalFormat df = new DecimalFormat("0.00");
        jLabel2.setText("" + df.format(prix));
    }

    public void Inventaire() {
        jLabel5.setVisible(true);
        ItemChoisi = "";
        jLabel4.setVisible(false);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jLabel13.setVisible(true);
        jLabel12.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jTextField1.setVisible(true);
        jTextField6.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField7.setVisible(true);
        jTextField8.setVisible(true);
        jTextField9.setVisible(true);
        jTextField11.setVisible(true);;
        jTextField10.setVisible(true);
        jComboBox2.setVisible(true);
        jComboBox2.setLocation(new Point(96, 360));
        jComboBox1.setVisible(true);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        jButton5.setVisible(true);
        // jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondDossierClient.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1260, 980);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuEmploye.png"))); // NOI18N
        CasePointee = -1;
        DatePointee = "";
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jTable2.setVisible(false);
        jScrollPane2.setVisible(false);
        jLabel1.setVisible(true);
    }

    public void valeurTextFileds(String[] Value) {
        ListTextFields.set(0, Value[0]);
        ListTextFields.set(0, Value[1]);
        ListTextFields.set(0, Value[2]);
    }

    public void RemplirLabel(String[] NomProduit) {
        jLabel8.setText(NomProduit[0]);
        System.out.println(jLabel8.getText());
        jLabel3.setText(NomProduit[1]);
        jLabel6.setText(NomProduit[2]);
        jLabel9.setText(NomProduit[3]);
        jLabel11.setText(NomProduit[4]);
        jLabel13.setText(NomProduit[5]);
        jLabel10.setText(NomProduit[6]);
        jLabel12.setText(NomProduit[7]);
        jLabel7.setText(NomProduit[8]);
    }

    public void modifierTextfields(int i, double prix) {
        if (i == 0) {
            jTextField4.setText("" + prix);
        } else if (i == 1) {
            jTextField5.setText("" + prix);
        } else if (i == 2) {
            jTextField6.setText("" + prix);
        } else if (i == 3) {
            jTextField7.setText("" + prix);
        } else if (i == 4) {
            jTextField8.setText("" + prix);
        } else if (i == 5) {
            jTextField9.setText("" + prix);
        } else if (i == 6) {
            jTextField10.setText("" + prix);
        } else if (i == 7) {
            jTextField11.setText("" + prix);
        } else if (i == 8) {
            jTextField1.setText("" + prix);
        }
        //  jTextField2.setText(Valeur[0]); //modification du prix unitaire
        // jTextField3.setText(Valeur[1]); //modification du prix unitaire

    }

    /* public String getjTextField1() {
        return jTextField1.toString();
    }

    public String getjTextField2() {
      //  return jTextField2.toString();
    }

    public String getjTextField3() {
       // return jTextField3.toString();
    }*/

 /*public void AfficherFond(int i) {
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuEmploye.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1260, 980);
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmployeMenu().setVisible(true);
            }
        });
    }

    public int BoutonDossierClient = 0;
    public int BoutonExamVente = 0;
    public int BoutonInventaire = 0;
    public int BoutonOffreRabais = 0;
    public String ItemChoisi = "";
    public String ProduitChoisi = "";
    public int CasePointee = -1;
    public String DatePointee = "";
    public int BoutonRetour = 0;
    public String Username = "";
    public javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    public javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    public javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    public ArrayList<String> ListTextFields = new ArrayList<>();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
